/* Native call profile recovered from this specific Slope build. */
function createSlopeBridge(M){
 const strings=new Map(),types=new Map();const scratch=M._malloc(128);
 function str(s){if(strings.has(s))return strings.get(s);const p=M._malloc(14+s.length*2);M.HEAPU8.fill(0,p,p+14+s.length*2);M.HEAPU32[(p+8)>>>2]=s.length;for(let i=0;i<s.length;i++)M.HEAPU16[((p+12)>>>1)+i]=s.charCodeAt(i);strings.set(s,p);return p;}
 function text(p){if(!p)return '';let n=M.HEAPU32[(p+8)>>>2];if(n>10000)return '';return String.fromCharCode(...M.HEAPU16.subarray((p+12)>>>1,((p+12)>>>1)+n));}
 function type(n){if(types.has(n))return types.get(n);let assembly=n==='Rigidbody'||n==='Collider'?'UnityEngine.PhysicsModule':'UnityEngine.CoreModule';const t=M.dynCall_iiii(1144,0,str(n.includes(',')?n:'UnityEngine.'+n+', '+assembly),0);if(!t)throw Error('Missing type '+n);types.set(n,t);return t;}
 function array(p){if(!p)return [];const n=M.HEAPU32[(p+12)>>>2];if(n>20000)throw Error('Invalid engine array');return Array.from(M.HEAPU32.subarray((p+16)>>>2,((p+16)>>>2)+n));}
 function all(n){return array(M.dynCall_ii(943,type(n)));}
 function component(go,n){return M.dynCall_iii(6237,go,type(n));}
 function find(n){return M.dynCall_ii(890,str(n));}
 function name(o){return text(M.dynCall_ii(944,o));}
 function transform(go){return M.dynCall_ii(882,go);}
 function vec(ptr,values){M.HEAPF32.set(values,ptr>>>2);return ptr;}
 function getV(fn,o){M.dynCall_vii(fn,o,scratch);return Array.from(M.HEAPF32.subarray(scratch>>>2,(scratch>>>2)+3));}
 function setV(fn,o,v){M.dynCall_vii(fn,o,vec(scratch,v));}
 const api={M,str,text,type,array,all,component,find,name,transform,vec,scratch,getV,setV,position(go){return getV(8976,transform(go));},setPosition(go,v){setV(8977,transform(go),v);},velocity(rb){return getV(9242,rb);},setVelocity(rb,v){setV(9243,rb,v);},active(go,on){M.dynCall_vii(8905,go,+on);},material(r){return M.dynCall_ii(947,r);},sharedMaterial(r){return M.dynCall_ii(948,r);},color(mat,rgba){M.dynCall_viii(5012,mat,M.dynCall_ii(925,str('_Color')),vec(scratch,rgba));}};
 return api;
}

function installSlopeMods(M){
 if(globalThis.SlopeMods)return globalThis.SlopeMods;
 const B=createSlopeBridge(M),u=a=>M.HEAPU32[a>>>2],f=a=>M.HEAPF32[a>>>2];
 const state={jumpEnabled:true,jumpPower:11,bot:false,ballColor:'#96ff32',mapColor:null,course:[],lastJump:-10000,botTarget:null,jumps:0,botSteps:0};
 let ball=0,rb=0,ballRenderer=0,ballMat=0,originalBallTex=0,customTex=0,imageMode=false,originalPixels=null,imagePixels=null,host,root,tickId,refreshId,disposed=false;
 const mapOriginals=new Map(),mapClones=new Map(),savedWrites=new Map();let courseProfile=null,lastTime=performance.now();
 function cstr(p){let e=p;while(M.HEAPU8[e]&&e<p+200)e++;return new TextDecoder().decode(M.HEAPU8.subarray(p,e));}
 function klass(p){return cstr(u(u(p)+8));}
 function write32(p,v){if(!savedWrites.has(p))savedWrites.set(p,u(p));M.HEAPU32[p>>>2]=v;}
 function rgba(hex){if(!/^#[0-9a-f]{6}$/i.test(hex))throw Error('Choose a valid color.');return [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255).concat(1);}
 function message(s){if(root)root.getElementById('mod-message').textContent=s;}
 function locate(){const next=B.find('Sphere');if(!next)return false;if(next!==ball){ball=next;rb=B.component(ball,'Rigidbody');ballRenderer=B.component(ball,'Renderer');ballMat=B.material(ballRenderer);originalBallTex=M.dynCall_iii(6250,ballMat,M.dynCall_ii(925,B.str('_MainTex')));}return !!rb;}
 function ray(origin,direction,distance){B.vec(B.scratch+32,origin);B.vec(B.scratch+48,direction);return !!M.dynCall_iiifii(18,B.scratch+32,B.scratch+48,distance,~(1<<4),1);}
 function grounded(){if(!locate())return false;const p=B.position(ball);return ray(p,[0,-1,0],.92)||ray(p,[0,-.7071,-.7071],.65);}
 function jump(){if(!state.jumpEnabled||!locate()||SlopePractice.get()===0||M.dynCall_ii(1014,rb))return false;const now=performance.now();if(now-state.lastJump<250||!grounded())return false;const v=B.velocity(rb);const impulse=Math.max(0,state.jumpPower-(v[1]+v[2])*.7071);v[1]+=impulse*.7071;v[2]+=impulse*.7071;B.setVelocity(rb,v);state.lastJump=now;state.jumps++;message('Jump!');return true;}
 function pixels(tex){const p=M.dynCall_iii(6253,tex,0),count=u(p+12);return new Uint8Array(M.HEAPU8.slice(p+16,p+16+count*4));}
 function putPixels(tex,data){const p=M._malloc(16+data.length);try{M.HEAPU8.fill(0,p,p+16);M.HEAPU32[(p+12)>>>2]=data.length/4;M.HEAPU8.set(data,p+16);M.dynCall_viii(5020,tex,p,0);M.dynCall_viii(5021,tex,1,0);}finally{M._free(p);}}
 function setTexture(mat,tex){M.dynCall_viii(5015,mat,M.dynCall_ii(925,B.str('_MainTex')),tex);}
 function tint(data,color,grayscale=true){const out=grayscale?gray(data):new Uint8Array(data);for(let i=0;i<out.length;i+=4){out[i]*=color[0];out[i+1]*=color[1];out[i+2]*=color[2];}return out;}
 function gray(data){const out=new Uint8Array(data);for(let i=0;i<out.length;i+=4){const v=Math.max(out[i],out[i+1],out[i+2]);out[i]=out[i+1]=out[i+2]=v;}return out;}
 function prepareBallTexture(){if(!locate())throw Error('Start the game first.');if(!customTex){originalPixels=pixels(originalBallTex);customTex=M.dynCall_ii(942,originalBallTex);}setTexture(ballMat,customTex);return customTex;}
 function setBallColor(hex){const color=rgba(hex);prepareBallTexture();if(!imageMode)putPixels(customTex,tint(originalPixels,color));else putPixels(customTex,tint(imagePixels,color,false));B.color(ballMat,[1,1,1,1]);state.ballColor=hex;message(imageMode?'Ball image tint updated.':'Ball color updated.');}
 async function setBallImage(file){if(!(file instanceof Blob)||file.size>12*1024*1024)throw Error('Choose an image smaller than 12 MB.');const bitmap=await createImageBitmap(file);try{if(bitmap.width*bitmap.height>40000000)throw Error('Image is too large.');prepareBallTexture();const width=M.dynCall_ii(932,customTex),height=M.dynCall_ii(933,customTex);const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');ctx.translate(0,height);ctx.scale(1,-1);ctx.drawImage(bitmap,0,0,width,height);imagePixels=new Uint8Array(ctx.getImageData(0,0,width,height).data);putPixels(customTex,imagePixels);M.dynCall_viii(5019,ballMat,M.dynCall_ii(925,B.str('_MainTex')),B.vec(B.scratch,[1,1]));B.color(ballMat,[1,1,1,1]);imageMode=true;message('Your image now wraps around the ball.');}finally{bitmap.close();}}
 function resetBall(){if(!locate())return;setTexture(ballMat,originalBallTex);M.dynCall_viii(5019,ballMat,M.dynCall_ii(925,B.str('_MainTex')),B.vec(B.scratch,[6,6]));B.color(ballMat,[.588,.588,.588,1]);imageMode=false;state.ballColor='#96ff32';}
 function colorMap(){if(!state.mapColor)return;const color=rgba(state.mapColor);for(const renderer of B.all('Renderer')){for(const mat of B.array(M.dynCall_ii(950,renderer))){if(!/^Ground(?:Arrows|Thin)?$/.test(B.name(mat)))continue;let orig=mapOriginals.get(mat);if(!orig){const tex=M.dynCall_iii(6250,mat,M.dynCall_ii(925,B.str('_MainTex')));orig={tex,pixels:pixels(tex)};mapOriginals.set(mat,orig);let clone=mapClones.get(tex);if(!clone){clone=M.dynCall_ii(942,tex);putPixels(clone,gray(pixels(tex)));mapClones.set(tex,clone);}setTexture(mat,clone);}if(orig.appliedColor!==state.mapColor){putPixels(mapClones.get(orig.tex),tint(orig.pixels,color));orig.appliedColor=state.mapColor;}B.color(mat,[1,1,1,1]);}}}
 function setMapColor(hex){rgba(hex);state.mapColor=hex;colorMap();message('Track color updated. Red hazards keep their warning color.');}
 function resetMap(){state.mapColor=null;for(const [mat,{tex}] of mapOriginals){setTexture(mat,tex);B.color(mat,[1,1,1,1]);}mapOriginals.clear();}
 const courseChoices=[['Obstacles','spawn easy obsticle'],['Narrow','spawn thin (remove jump)'],['Tilted track','spawn tilt left'],['Five obstacles','spawn 5 obsticles'],['Danger tunnel','spawn death tunnel'],['Dogleg bends','Move Spawn Forward & Down'],['Vertical obstacles','spawn vertical obsticles'],['Narrow switch','spawn thin switch'],['Side obstacles','spawn horiz obsticles']];
 function getCourse(){if(courseProfile)return courseProfile;const go=B.find('t_Spawner');if(!go)throw Error('Start the game first.');const comp=B.component(go,'PlayMakerFSM, PlayMaker'),fsm=u(comp+12),states=B.array(u(fsm+32)),byName=new Map(states.map(st=>[B.text(u(st+24)),st]));const groups=['easy run','medium run','hard run'].map(name=>{const st=byName.get(name),action=B.array(u(st+60)).find(a=>klass(a)==='SendRandomEvent');return {st,transitions:B.array(u(st+56)),events:B.array(u(action+40)),weights:B.array(u(action+44))};});courseProfile={fsm,byName,groups};return courseProfile;}
 function setCourse(names){if(!Array.isArray(names)||names.length>3||names.some(n=>!courseChoices.some(c=>c[1]===n)))throw Error('Choose one to three course sections.');resetCourse();if(!names.length)return;const p=getCourse();for(const group of p.groups){for(let i=0;i<group.events.length;i++){const transition=group.transitions.find(t=>u(t+8)===group.events[i]);if(!transition)throw Error('Course transition does not match this build.');write32(transition+12,u(p.byName.get(names[i%names.length])+24));const ptr=group.weights[i]+24;write32(ptr,i<names.length?0x3f800000:0);}}for(const [label,st] of p.byName){if(label.startsWith('Repeat'))for(const tr of B.array(u(st+56))){if(B.text(u(u(tr+8)+8))==='Next Run')write32(tr+12,u(p.byName.get('spawn tunnel run')+24));}}state.course=names.slice();message('Course filter applied to future sections. Existing tunnels and connectors remain.');}
 function resetCourse(){for(const [p,v] of savedWrites)M.HEAPU32[p>>>2]=v;savedWrites.clear();state.course=[];}
 function bot(dt){if(!locate()||M.dynCall_ii(1014,rb))return;const pos=B.position(ball),v=B.velocity(rb);if(v[2]<1)return;const ahead=Math.max(2,Math.min(9,v[2]*.23));let best=null,bestScore=-Infinity;for(let dx=-3;dx<=3;dx+=.6){const x=pos[0]+dx;const support=ray([x,pos[1]-ahead+4,pos[2]+ahead],[0,-1,0],6);if(!support)continue;const length=Math.hypot(dx,ahead,ahead);const blocked=ray([pos[0],pos[1]+.2,pos[2]],[dx/length,-ahead/length,ahead/length],length);const score=(blocked?-20:20)-Math.abs(dx)*1.4-Math.abs(dx-v[0]*.2)*.7;if(score>bestScore){bestScore=score;best={x,blocked};}}
 if(best){state.botTarget=best.x;const wanted=Math.max(-10,Math.min(10,(best.x-pos[0])*5));v[0]+=Math.max(-1,Math.min(1,(wanted-v[0])*.35))*Math.min(1,dt*60);B.setVelocity(rb,v);if(best.blocked)jump();}else{state.botTarget=null;if(grounded())jump();}state.botSteps++;}
 function frame(now){if(disposed)return;const dt=Math.min(.05,(now-lastTime)/1000);lastTime=now;try{if(state.bot&&SlopePractice.get()>0)bot(dt);}catch(e){state.bot=false;message('Bot stopped: '+e.message);}tickId=requestAnimationFrame(frame);}
 function key(e){const target=e.composedPath()[0];if(target&&/INPUT|TEXTAREA|SELECT|BUTTON/.test(target.tagName))return;if(e.code==='Space'){e.preventDefault();if(!e.repeat)jump();}if(e.code==='KeyB'&&!e.repeat){state.bot=!state.bot;root.getElementById('bot').checked=state.bot;message(state.bot?'Autopilot on. Press B to take control.':'Autopilot off.');}}
 function mount(){host=document.createElement('div');host.id='slope-mod-panel';host.style.cssText='position:fixed;left:14px;top:70px;z-index:2147483645';root=host.attachShadow({mode:'open'});document.body.appendChild(host);root.innerHTML=`<style>:host{all:initial;font:13px system-ui;color:#e7f0e5}*{box-sizing:border-box}.panel{width:255px;max-height:calc(100vh - 95px);overflow:auto;background:#14241bf5;border:1px solid #72876a;border-radius:12px;padding:15px;box-shadow:0 8px 30px #0008}h3{font-size:16px;margin:0 0 12px}label{display:block;margin:9px 0}summary{cursor:pointer;font-weight:650;margin:13px 0}button,select{font:inherit;border:1px solid #718963;border-radius:5px;background:#31482d;color:#eef9e8;padding:8px;cursor:pointer}button{margin:4px 2px}input[type=range],input[type=file]{width:100%}input[type=color]{vertical-align:middle;width:48px;height:26px;border:0}p{font-size:11px;line-height:1.45;color:#bccdb6}.choices label{font-size:11px}#open{display:none}#mod-message{color:#d8ed9c}#telemetry{font-variant-numeric:tabular-nums}</style><button id="open">Mods</button><div class="panel" id="panel"><h3>Slope workshop</h3><label><input id="jump-enabled" type="checkbox" checked> Jump with Space</label><button id="jump">Jump</button><label>Jump strength <input id="jump-power" type="range" min="6" max="22" value="11"></label><label><input id="bot" type="checkbox"> Autopilot (B)</label><p>The bot looks for track ahead and steers or jumps. It can still miss gaps and obstacles.</p><p id="telemetry">Waiting for the ball…</p><details><summary>Ball & map appearance</summary><label>Ball color <input id="ball-color" type="color" value="#96ff32"></label><label>Map color <input id="map-color" type="color" value="#00ff00"></label><label>Ball image <input id="ball-image" type="file" accept="image/*"></label><p>Images wrap around the sphere. Color also tints an uploaded image.</p><button id="ball-reset">Reset ball</button><button id="map-reset">Reset map</button></details><details><summary>Custom course filter</summary><p>Pick up to three section types. The generator uses them for future runs; existing sections and connecting tunnels remain. Tilted tracks and doglegs include their alternating variants.</p><div class="choices">${courseChoices.map(([label,name],i)=>`<label><input type="checkbox" data-course="${i}"> ${label}</label>`).join('')}</div><button id="course-apply">Apply filter</button><button id="course-reset">Original course</button><button id="save">Export settings</button><label>Import settings <input id="load" type="file" accept=".json,application/json"></label></details><p id="mod-message">Play the game, then try a control.</p><button id="hide">Hide workshop</button></div>`;
 const el=id=>root.getElementById(id),run=fn=>async()=>{try{await fn();}catch(e){message(e.message||String(e));}};
 el('jump').onclick=()=>{if(!jump())message('Jump after the ball lands.');};el('jump-enabled').onchange=e=>state.jumpEnabled=e.target.checked;el('jump-power').oninput=e=>state.jumpPower=+e.target.value;el('bot').onchange=e=>state.bot=e.target.checked;
 el('ball-color').oninput=run(()=>setBallColor(el('ball-color').value));el('map-color').oninput=run(()=>setMapColor(el('map-color').value));el('ball-image').onchange=run(()=>setBallImage(el('ball-image').files[0]));el('ball-reset').onclick=run(resetBall);el('map-reset').onclick=run(resetMap);
 el('course-apply').onclick=run(()=>setCourse([...root.querySelectorAll('[data-course]:checked')].map(e=>courseChoices[+e.dataset.course][1])));el('course-reset').onclick=()=>{resetCourse();for(const c of root.querySelectorAll('[data-course]'))c.checked=false;message('Original procedural course restored.');};
 el('save').onclick=()=>{const data={version:1,speed:SlopePractice.get(),jumpEnabled:state.jumpEnabled,jumpPower:state.jumpPower,ballColor:state.ballColor,mapColor:state.mapColor,course:state.course};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='slope-settings.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 el('load').onchange=run(async()=>{const file=el('load').files[0];if(!file||file.size>10000)throw Error('Invalid settings file.');const d=JSON.parse(await file.text());if(d.version!==1||!Number.isFinite(d.speed)||d.speed<0||d.speed>8||!Number.isFinite(d.jumpPower)||d.jumpPower<6||d.jumpPower>22||typeof d.jumpEnabled!=='boolean'||!Array.isArray(d.course)||d.course.length>3||d.course.some(n=>!courseChoices.some(c=>c[1]===n)))throw Error('Invalid settings.');rgba(d.ballColor);if(d.mapColor)rgba(d.mapColor);setCourse(d.course);setBallColor(d.ballColor);if(d.mapColor)setMapColor(d.mapColor);else resetMap();SlopePractice.set(d.speed);state.jumpEnabled=d.jumpEnabled;state.jumpPower=d.jumpPower;el('jump-enabled').checked=d.jumpEnabled;el('jump-power').value=d.jumpPower;el('ball-color').value=d.ballColor;if(d.mapColor)el('map-color').value=d.mapColor;for(const c of root.querySelectorAll('[data-course]'))c.checked=d.course.includes(courseChoices[+c.dataset.course][1]);message('Settings imported. Images are selected separately.');});
 el('hide').onclick=()=>{el('panel').style.display='none';el('open').style.display='block';};el('open').onclick=()=>{el('panel').style.display='block';el('open').style.display='none';};
 document.addEventListener('keydown',key,{capture:true});tickId=requestAnimationFrame(frame);refreshId=setInterval(()=>{try{if(locate()){const v=B.velocity(rb);el('telemetry').textContent=`Ball speed: ${Math.hypot(...v).toFixed(1)} · ${grounded()?'Grounded':'Airborne'}`;colorMap();}}catch(e){message(e.message||String(e));}},500);
 }
 const api={B,state,locate,grounded,jump,ray,setBallColor,setBallImage,resetBall,setMapColor,resetMap,setCourse,resetCourse,courseChoices,getCourse,setBot(on){state.bot=!!on;if(root)root.getElementById('bot').checked=state.bot;},status(){return {ball,rb,velocity:rb?B.velocity(rb):null,position:ball?B.position(ball):null,imageMode,customTex,grounded:grounded(),...state};},dispose(){disposed=true;cancelAnimationFrame(tickId);clearInterval(refreshId);document.removeEventListener('keydown',key,{capture:true});resetCourse();resetMap();resetBall();host?.remove();}};
 globalThis.SlopeMods=api;mount();return api;
}
