const {FFmpeg}=FFmpegWASM; const {fetchFile,toBlobURL}=FFmpegUtil;
const $=id=>document.getElementById(id); let media=[],clips=[],selected=-1,photos=[]; let ffmpeg=null;
const mediaInput=$('mediaInput'),photoInput=$('photoInput'),drop=$('drop');
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function addMedia(files){for(const file of files){if(!/^(video|audio|image)\//.test(file.type))continue;const m={file,url:URL.createObjectURL(file),name:file.name,type:file.type};media.push(m);if(file.type.startsWith('video/')||file.type.startsWith('image/'))addClip(m)}renderMedia()}
function renderMedia(){$('media').innerHTML=media.map((m,i)=>`<div class="mediaItem" data-i="${i}">📄 <b>${esc(m.name)}</b><small>${m.type}</small></div>`).join('');document.querySelectorAll('.mediaItem').forEach(x=>x.onclick=()=>{const m=media[x.dataset.i];$('preview').src=m.url;$('preview').style.display=m.type.startsWith('video/')?'block':'none'})}
function addClip(m){clips.push({...m,start:0,end:null});selected=clips.length-1;renderTimeline();loadSelected()}
function renderTimeline(){$('track').innerHTML=clips.map((c,i)=>`<div class="clip ${i===selected?'selected':''}" data-i="${i}"><b>${esc(c.name)}</b><small>${c.end!=null?Math.max(0,c.end-c.start).toFixed(2)+'s':'media'}</small></div>`).join('');document.querySelectorAll('.clip').forEach(x=>x.onclick=()=>{selected=+x.dataset.i;renderTimeline();loadSelected()})}
function loadSelected(){if(selected<0)return;const c=clips[selected];$('preview').src=c.url;$('preview').style.display=c.type.startsWith('video/')?'block':'none';$('name').value=c.name;$('start').value=c.start||0;$('end').value=c.end??'';$('status').textContent=`Selected: ${c.name}`;$('preview').onloadedmetadata=()=>{if(c.end==null)$('end').value=$('preview').duration.toFixed(2)}}
$('apply').onclick=()=>{if(selected<0)return;const c=clips[selected];c.name=$('name').value||c.name;c.start=+$('start').value||0;c.end=+$('end').value||0;renderTimeline();loadSelected()};$('remove').onclick=()=>{if(selected<0)return;clips.splice(selected,1);selected=Math.min(selected,clips.length-1);renderTimeline();if(selected>=0)loadSelected()};
mediaInput.onchange=e=>addMedia([...e.target.files]);drop.onclick=()=>mediaInput.click();drop.ondragover=e=>{e.preventDefault();drop.classList.add('over')};drop.ondragleave=()=>drop.classList.remove('over');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('over');addMedia([...e.dataTransfer.files])};
photoInput.onchange=e=>{photos=[...e.target.files];$('photoCount').textContent=`${photos.length} photos selected. At 30 FPS, each photo is 1/30 second.`;$('photoDialog').classList.add('show')};$('cancelPhoto').onclick=()=>$('photoDialog').classList.remove('show');
async function photoVideo(){const fps=Math.max(1,+$('fps').value||30);const canvas=$('canvas'),ctx=canvas.getContext('2d');canvas.width=1280;canvas.height=720;canvas.style.display='block';$('preview').style.display='none';const stream=canvas.captureStream(fps);const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm';const rec=new MediaRecorder(stream,{mimeType:mime});const chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.start();for(let i=0;i<photos.length;i++){const img=new Image();img.src=URL.createObjectURL(photos[i]);await new Promise(r=>img.onload=r);ctx.fillStyle='#000';ctx.fillRect(0,0,1280,720);const s=Math.min(1280/img.width,720/img.height);const w=img.width*s,h=img.height*s;ctx.drawImage(img,(1280-w)/2,(720-h)/2,w,h);URL.revokeObjectURL(img.src);$('photoStatus').textContent=`Creating ${i+1}/${photos.length}...`;await new Promise(r=>setTimeout(r,1000/fps))}rec.stop();await new Promise(r=>rec.onstop=r);stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:mime});const file=new File([blob],'photos-video.webm',{type:mime});addMedia([file]);$('canvas').style.display='none';$('photoDialog').classList.remove('show')}
$('makePhotoVideo').onclick=photoVideo;
async function loadFFmpeg(){if(ffmpeg)return;ffmpeg=new FFmpeg();$('status').textContent='Loading FFmpeg.wasm...';const base='https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.12.6/dist/umd';await ffmpeg.load({coreURL:await toBlobURL(`${base}/ffmpeg-core.js`,'text/javascript'),wasmURL:await toBlobURL(`${base}/ffmpeg-core.wasm`,'application/wasm'),workerURL:await toBlobURL(`${base}/ffmpeg-core.worker.js`,'text/javascript')});$('status').textContent='FFmpeg ready.'}
async function exportVideo(){if(!clips.length){$('status').textContent='Add clips first.';return}await loadFFmpeg();$('progress').textContent='Rendering timeline...';const inputs=[];for(let i=0;i<clips.length;i++){const c=clips[i];const ext=c.name.split('.').pop().toLowerCase();const name=`in${i}.${ext||'mp4'}`;await ffmpeg.writeFile(name,await fetchFile(c.file));inputs.push({name:c.name,file:name,start:c.start||0,end:c.end});}
// Build a concat filter. Images are looped; videos are trimmed. Audio is preserved when present.
let filter='',maps='';for(let i=0;i<inputs.length;i++){const c=clips[i],d=(c.end!=null&&c.end>c.start)?c.end-c.start:0;if(c.type.startsWith('image/')){filter+=`[${i}:v]scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2,format=yuv420p,setsar=1[v${i}];`;maps+=`[v${i}]`;}else{filter+=`[${i}:v]trim=start=${c.start||0}${d?`:end=${c.end}`:''},setpts=PTS-STARTPTS,scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2,format=yuv420p,setsar=1[v${i}];`;maps+=`[v${i}]`}}
filter+=maps+`concat=n=${clips.length}:v=1:a=0[outv]`;const args=[];for(const x of inputs)args.push('-i',x.file);args.push('-filter_complex',filter,'-map','[outv]','-r','30','-c:v','libvpx-vp9','-b:v','2M','out.webm');try{await ffmpeg.exec(args);const data=await ffmpeg.readFile('out.webm');const url=URL.createObjectURL(new Blob([data.buffer],{type:'video/webm'}));const a=document.createElement('a');a.href=url;a.download='edited-video.webm';a.click();$('status').textContent='Export finished!'}catch(e){console.error(e);$('status').textContent='Export failed. Check the browser console.'}$('progress').textContent=''}
$('export').onclick=exportVideo;
